In [1]:
#1. Array Creation:
#a.Create a 1-dimensional array of integers from 1 to 10.
import numpy as np
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
# b. Create a 2-dimensional array with random float values of shape (3, 4).
arr1=np.random.rand(3,4)
arr1

array([[0.22806476, 0.27358814, 0.52419281, 0.96307895],
       [0.89592704, 0.52583382, 0.62041574, 0.26221097],
       [0.242288  , 0.80074249, 0.41448198, 0.52159577]])

In [7]:
arr2=np.random.rand(2,3,4)
arr2

array([[[0.61212843, 0.24932527, 0.29136646, 0.14049317],
        [0.98349193, 0.73565917, 0.594063  , 0.03645166],
        [0.4801778 , 0.39544112, 0.46316139, 0.42889958]],

       [[0.47563487, 0.28747662, 0.15620399, 0.67637788],
        [0.51917335, 0.8487142 , 0.35933268, 0.88851669],
        [0.57400253, 0.52119549, 0.67521625, 0.55342313]]])

In [18]:
#2. Array Operations:
#Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.
a=np.array([6,7,8,9,10])
b=np.array([1,2,3,4,5])
c=a+b
d=a-b
e=a*b
f=a/b
print("sum is:",c)
print("subtractionis:",d)
print("product is:",e)
print("division is:",f)


sum is: [ 7  9 11 13 15]
subtractionis: [5 5 5 5 5]
product is: [ 6 14 24 36 50]
division is: [6.         3.5        2.66666667 2.25       2.        ]


In [ ]:
#b.Calculate the mean, median, and standard deviation of a given 1-dimensional array.

In [7]:
import numpy as np
a=np.array([2,4,6,8,10])
mean=np.mean(a)
median=np.median(a)
standard_dev=np.std(a)
print("Mean:",mean)
print("Median:",median)
print("standard Deviation:",standard_dev)

Mean: 6.0
Median: 6.0
standard Deviation: 2.8284271247461903


In [17]:
#c.Reshape a 1-dimensional array into a 2-dimensional array of shape (3,4).
import numpy as np
arr3= np.array([1,2,3,4,5,6,7,23,45,65,11,22])
reshaped_array=arr3.reshape(3,4)
print("reshaped Array:",reshaped_array)

reshaped Array: [[ 1  2  3  4]
 [ 5  6  7 23]
 [45 65 11 22]]


In [19]:
#3. Array Indexing and Slicing:
#a.Extract the first row and last column of a 2-dimensional array.
import numpy as np
arr4=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
first_row=arr4[0,:]
last_row=arr4[3,:]
print("First Row:",first_row)
print("last Row:",last_row)

First Row: [1 2 3]
last Row: [10 11 12]


In [23]:
#b.Reverse the order of elements in a 1-dimensional array.
import numpy as np
arr5=np.array([5,6,7,8])
reverse=arr5[-1::-1]
print("Reverse:",reverse)

Reverse: [8 7 6 5]


In [25]:
#c.Select elements from a 2-dimensional array that satisfy a specific condition (e.g., values greater than a certain threshold).
import numpy as np
arr6=np.array([[1,2,3],[4,5,6],[7,8,9]])
threshold=5
elements=arr6[arr6>threshold]
print("Elements greater than threshold:",elements)

Elements greater than threshold: [6 7 8 9]


In [31]:
#4. Array Broadcasting:
#a.Add a scalar value to each element of a 2-dimensional array.
import numpy as np
arr7=np.array([[1,2,3],[4,5,6]])
scalar=10
result=arr7+scalar
print("Array after adding scalar:",result)

Array after adding scalar: [[11 12 13]
 [14 15 16]]


In [33]:
#b.Multiply a 1-dimensional array with a 2-dimensional array, leveraging NumPy's broadcasting rules.
one_dim=np.array([1,2,3])
two_dim=np.array([[4,5,6],[7,8,9]])
result=one_dim*two_dim
print(result)

[[ 4 10 18]
 [ 7 16 27]]


In [5]:
#5. Linear Algebra:
#a. Calculate the dot product of two 1-dimensional arrays.
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
dot_product=np.dot(a,b)
print("Dot Product:",dot_product)


Dot Product: 32


In [7]:
#b.Compute the matrix multiplication of two 2-dimensional arrays.
import numpy as np
x=np.array([[1,2,4],[3,4,6],[7,8,10]])
y=np.array([[12,13,14],[16,17,18],[19,22,23]])
result=np.dot(x,y)
print("Matrix Multiplication:",result)



Matrix Multiplication: [[120 135 142]
 [214 239 252]
 [402 447 472]]


In [11]:
#c.Find the inverse and determinant of a square matrix.
import numpy as np
a=np.array([[1,2,],[3,4]])
determinant=np.linalg.det(a)
print("Determinant:", determinant)

if determinant!=0:
    inverse=np.linalg.inv(a)
    print("Inverse:",inverse)
else:
    print("the matrix is singular,so it doesnot have an inverse.")



Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
